name: hello-world test
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
permissions:
    contents: read
    statuses: write
    checks: write
    pull-requests: write
jobs:
    echo-job:
        runs-on: [self-hosted, Linux, X64]
        steps:
            - name: Echo Hello World
              run: |
                yum install -y python3 && python3 -c 'print("Hello, World!")'
                mkdir -p output && echo "Hello, World!" > output/hello.txt
              env:
                VALIDATE_YAML: false
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}