name: hello-world test
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
    echo-job:
        runs-on: [self-hosted, linux, x6]
        steps:
            - name: Echo Hello World
              run: echo "Hello, World!"
              env:
                VALIDATE_YAML: false
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}